  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong(!)Password"
      MSSQL_PID: "Express"
    ports:
    - "1431:1433"
    volumes:
    - "sqlserver-data:/var/opt/mssql"
    restart: always
